# Generated by Django 5.2.13 on 2026-04-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], default='car', max_length=20)),
                ('model', models.CharField(max_length=120)),
                ('generation', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_code', models.CharField(blank=True, max_length=80)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('cng', 'CNG'), ('other', 'Other')], max_length=20)),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('power_kw', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__name', 'model', 'generation', 'variant', 'year_start'],
            },
        ),
        migrations.CreateModel(
            name='ProductVehicleFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitment_notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('supplier', 'Supplier'), ('import', 'Import'), ('manual', 'Manual')], default='import', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['product__sku', 'vehicle__brand__name', 'vehicle__model'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type', 'brand'], name='veh_type_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['model', 'year_start', 'year_end'], name='veh_model_year_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['engine_code'], name='vehicles_vehicle_engine_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('year_end__isnull', True), ('year_start__isnull', True), ('year_end__gte', models.F('year_start')), _connector='OR'), name='vehicles_vehicle_year_range_ck'),
        ),
        migrations.AddIndex(
            model_name='productvehiclefitment',
            index=models.Index(fields=['product', 'is_verified'], name='veh_fit_prod_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='productvehiclefitment',
            index=models.Index(fields=['vehicle', 'is_verified'], name='veh_fit_veh_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='productvehiclefitment',
            index=models.Index(fields=['source', 'is_verified'], name='veh_fit_src_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvehiclefitment',
            constraint=models.UniqueConstraint(fields=('product', 'vehicle'), name='vehicles_fitment_product_vehicle_uq'),
        ),
    ]
