# Generated by Django 5.2.13 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvehiclefitment',
            options={'ordering': ['product__sku', 'vehicle__brand__name', 'vehicle__model'], 'verbose_name': 'compatibilidad con vehículo', 'verbose_name_plural': 'compatibilidades con vehículos'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['brand__name', 'model', 'generation', 'variant', 'year_start'], 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='fitment_notes',
            field=models.TextField(blank=True, verbose_name='notas de compatibilidad'),
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='verificada'),
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='source',
            field=models.CharField(choices=[('supplier', 'Proveedor'), ('import', 'Importación'), ('manual', 'Manual')], default='import', max_length=20, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasolina'), ('diesel', 'Diésel'), ('hybrid', 'Híbrido'), ('electric', 'Eléctrico'), ('lpg', 'LPG'), ('cng', 'CNG'), ('other', 'Otro')], max_length=20, verbose_name='combustible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='generation',
            field=models.CharField(blank=True, max_length=120, verbose_name='generación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=120, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=120, verbose_name='versión'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Coche'), ('motorcycle', 'Moto'), ('truck', 'Camión'), ('van', 'Furgoneta'), ('other', 'Otro')], default='car', max_length=20, verbose_name='tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año final'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año inicial'),
        ),
    ]
