# Generated by Django 5.2.13 on 2026-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_attributedefinition_allows_multiple_values_and_more'),
        ('vehicles', '0002_alter_productvehiclefitment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='productvehiclefitment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='vehicles.vehicle', verbose_name='vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='catalog.brand', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='displacement_cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cilindrada (cc)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='potencia (CV)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='potencia (kW)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
