# Generated by Django 5.2.13 on 2026-04-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_alter_product_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_code", models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ("guest_name", models.CharField(blank=True, max_length=150)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=180)),
                ("tax_id", models.CharField(blank=True, max_length=64)),
                ("language", models.CharField(choices=[("es", "Spanish"), ("en", "English")], default="es", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("supplier_pending", "Supplier Pending"),
                            ("responded", "Responded to Customer"),
                            ("accepted", "Accepted by Customer"),
                            ("rejected", "Rejected by Customer"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=24,
                    ),
                ),
                ("notes_from_customer", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("response_due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("supplier_feedback_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="inq_status_created_idx"),
                    models.Index(fields=["status", "response_due_at"], name="inq_status_due_idx"),
                    models.Index(fields=["user", "status"], name="inq_user_status_idx"),
                    models.Index(fields=["guest_email"], name="inq_guest_email_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            models.Q(("guest_name__gt", ""), ("guest_email__gt", ""), _connector="AND"),
                            _connector="OR",
                        ),
                        name="inq_user_or_guest_contact_ck",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InquiryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_quantity", models.PositiveIntegerField(default=1)),
                ("customer_note", models.TextField(blank=True)),
                (
                    "last_known_price_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiry_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["inquiry_id", "id"],
                "indexes": [
                    models.Index(fields=["inquiry", "product"], name="inq_item_inquiry_product_idx"),
                    models.Index(fields=["product", "created_at"], name="inq_item_product_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("requested_quantity__gte", 1)),
                        name="inq_item_quantity_gte_1_ck",
                    ),
                    models.UniqueConstraint(
                        fields=("inquiry", "product"),
                        name="inq_item_inquiry_product_uq",
                    ),
                ],
            },
        ),
    ]
