# Generated by Django 5.2.13 on 2026-04-14 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted by Customer'), ('rejected', 'Rejected by Customer')], db_index=True, default='draft', max_length=16)),
                ('confirmed_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('lead_time_text', models.CharField(blank=True, max_length=255)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_message', models.TextField(blank=True)),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='inq_offer_status_sent_idx'), models.Index(fields=['status', 'created_at'], name='inq_offer_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confirmed_total__gte', 0)), name='inq_offer_total_gte_0_ck')],
            },
        ),
    ]
