# Generated by Django 5.2.13 on 2026-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryoffer',
            name='confirmed_total',
            field=models.DecimalField(decimal_places=2, help_text='Final confirmed commercial total for this offer. This is the source of truth for later payment preparation.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='currency',
            field=models.CharField(default='EUR', help_text='ISO 4217 currency code for the confirmed total amount.', max_length=3),
        ),
    ]
