# Generated by Django 5.2.13 on 2026-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiryoffer_confirmed_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='negative_resolution_customer_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='negative_resolution_internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='negative_resolution_reason',
            field=models.CharField(blank=True, choices=[('unavailable', 'Unavailable'), ('supplier_cannot_confirm', 'Supplier Cannot Confirm'), ('logistics_not_possible', 'Logistics Not Possible'), ('other', 'Other')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='negative_resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
