# Generated by Django 5.2.13 on 2026-04-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_inquiry_negative_resolution_customer_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryOfferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('provider', models.CharField(default='manual', max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('internal_notes', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='inquiries.inquiryoffer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'initiated_at'], name='inq_pay_status_init_idx'), models.Index(fields=['status', 'created_at'], name='inq_pay_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('payable_amount__gt', 0)), name='inq_offer_payment_amount_gt_0_ck')],
            },
        ),
    ]
