# Generated by Django 5.2.13 on 2026-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_inquiryofferpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryoffer',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='offer_response_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='payment_deadline_hours_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='response_deadline_hours_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiryofferpayment',
            name='payment_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted by Customer'), ('rejected', 'Rejected by Customer'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddIndex(
            model_name='inquiryoffer',
            index=models.Index(fields=['status', 'offer_response_deadline_at'], name='inq_offer_status_respdl_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryofferpayment',
            index=models.Index(fields=['status', 'payment_deadline_at'], name='inq_pay_status_deadl_idx'),
        ),
    ]
