# Generated by Django 5.2.13 on 2026-04-23 11:02

from datetime import timedelta

from django.db import migrations


DEFAULT_DEADLINE_HOURS = 24


def _resolve_supplier_deadline_hours(*, Supplier, inquiry_id: int) -> tuple[int, int]:
    supplier_deadline_rows = Supplier.objects.filter(
        products__inquiry_items__inquiry_id=inquiry_id
    ).values_list(
        "offer_response_deadline_hours",
        "accepted_payment_deadline_hours",
    ).distinct()
    response_candidates: list[int] = []
    payment_candidates: list[int] = []
    for response_hours, payment_hours in supplier_deadline_rows:
        if isinstance(response_hours, int) and response_hours > 0:
            response_candidates.append(response_hours)
        if isinstance(payment_hours, int) and payment_hours > 0:
            payment_candidates.append(payment_hours)
    response_deadline_hours = min(response_candidates) if response_candidates else DEFAULT_DEADLINE_HOURS
    payment_deadline_hours = min(payment_candidates) if payment_candidates else DEFAULT_DEADLINE_HOURS
    return response_deadline_hours, payment_deadline_hours


def backfill_deadline_snapshots(apps, schema_editor):
    del schema_editor
    Supplier = apps.get_model("suppliers", "Supplier")
    InquiryOffer = apps.get_model("inquiries", "InquiryOffer")
    InquiryOfferPayment = apps.get_model("inquiries", "InquiryOfferPayment")

    offer_statuses = {"sent", "accepted", "rejected"}
    offers = InquiryOffer.objects.filter(status__in=offer_statuses).order_by("pk")
    for offer in offers.iterator(chunk_size=200):
        (
            response_deadline_hours,
            payment_deadline_hours,
        ) = _resolve_supplier_deadline_hours(
            Supplier=Supplier,
            inquiry_id=offer.inquiry_id,
        )
        changed_fields: list[str] = []
        if not offer.response_deadline_hours_snapshot:
            offer.response_deadline_hours_snapshot = response_deadline_hours
            changed_fields.append("response_deadline_hours_snapshot")
        if not offer.payment_deadline_hours_snapshot:
            offer.payment_deadline_hours_snapshot = payment_deadline_hours
            changed_fields.append("payment_deadline_hours_snapshot")
        if offer.offer_response_deadline_at is None:
            sent_anchor = offer.sent_at or offer.created_at
            if sent_anchor is not None:
                offer.offer_response_deadline_at = sent_anchor + timedelta(
                    hours=response_deadline_hours
                )
                changed_fields.append("offer_response_deadline_at")
        if changed_fields:
            offer.save(update_fields=changed_fields)

    pending_payments = InquiryOfferPayment.objects.filter(
        status="pending",
        payment_deadline_at__isnull=True,
    ).select_related("offer")
    for payment in pending_payments.iterator(chunk_size=200):
        offer = payment.offer
        payment_deadline_hours = offer.payment_deadline_hours_snapshot or DEFAULT_DEADLINE_HOURS
        accepted_anchor = offer.accepted_at or payment.initiated_at or payment.created_at
        payment.payment_deadline_at = accepted_anchor + timedelta(hours=payment_deadline_hours)
        payment.save(update_fields=["payment_deadline_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_supplier_accepted_payment_deadline_hours_and_more"),
        ("inquiries", "0006_inquiryoffer_expired_at_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_deadline_snapshots, migrations.RunPython.noop),
    ]
