# Generated by Django 5.2.13 on 2026-07-15 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_backfill_deadline_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquirySubmissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=150)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5)),
                ('notes_from_customer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_submission_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='submission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='inquiries.inquirysubmissiongroup'),
        ),
        migrations.AddIndex(
            model_name='inquirysubmissiongroup',
            index=models.Index(fields=['user', 'created_at'], name='inq_group_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirysubmissiongroup',
            index=models.Index(fields=['guest_email'], name='inq_group_guest_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='inquirysubmissiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('guest_name__gt', ''), ('guest_email__gt', '')), _connector='OR'), name='inq_group_user_or_guest_contact_ck'),
        ),
    ]
