# Generated by Django 5.2.13 on 2026-07-15 10:35

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_inquirysubmissiongroup_inquiry_submission_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='quoted_destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='quoted_destination_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='quoted_destination_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inquirysubmissiongroup',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='inquirysubmissiongroup',
            name='destination_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inquirysubmissiongroup',
            name='destination_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='confirmed_total',
            field=models.DecimalField(decimal_places=2, help_text='Final confirmed commercial total for this offer. This is the source of truth for later payment preparation and must include shipping calculated for the quoted destination when applicable.', max_digits=12),
        ),
        migrations.CreateModel(
            name='InquiryOfferPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_recipient_name', models.CharField(max_length=180)),
                ('shipping_phone', models.CharField(max_length=50)),
                ('shipping_address_line_1', models.CharField(max_length=255)),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_region', models.CharField(max_length=120)),
                ('shipping_postal_code', models.CharField(max_length=32)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_customer_type', models.CharField(choices=[('private', 'Private individual'), ('company', 'Company / legal entity')], default='private', max_length=16)),
                ('billing_same_as_shipping', models.BooleanField(default=True)),
                ('billing_name', models.CharField(max_length=180)),
                ('billing_tax_id', models.CharField(blank=True, max_length=64)),
                ('billing_address_line_1', models.CharField(max_length=255)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(max_length=120)),
                ('billing_region', models.CharField(max_length=120)),
                ('billing_postal_code', models.CharField(max_length=32)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_details', to='inquiries.inquiryofferpayment')),
            ],
            options={
                'verbose_name_plural': 'inquiry offer payment details',
            },
        ),
    ]
