# Generated by Django 5.2.13 on 2026-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_inquiry_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='quoted_destination_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inquirysubmissiongroup',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
