# Generated by Django 5.2.13 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_inquiry_destination_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='inquiryitem',
            options={'ordering': ['inquiry_id', 'id'], 'verbose_name': 'artículo solicitado', 'verbose_name_plural': 'artículos solicitados'},
        ),
        migrations.AlterModelOptions(
            name='inquiryoffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
        migrations.AlterModelOptions(
            name='inquiryofferpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
        migrations.AlterModelOptions(
            name='inquiryofferpaymentdetails',
            options={'verbose_name': 'datos de envío y facturación', 'verbose_name_plural': 'datos de envío y facturación'},
        ),
        migrations.AlterModelOptions(
            name='inquirysubmissiongroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'grupo de solicitudes', 'verbose_name_plural': 'grupos de solicitudes'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico del cliente'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='notas internas'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=5, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='negative_resolution_reason',
            field=models.CharField(blank=True, choices=[('unavailable', 'No disponible'), ('supplier_cannot_confirm', 'El proveedor no puede confirmar'), ('logistics_not_possible', 'Logística no viable'), ('other', 'Otro motivo')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='notes_from_customer',
            field=models.TextField(blank=True, verbose_name='notas del cliente'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='reference_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='código de referencia'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('in_review', 'En revisión'), ('supplier_pending', 'Pendiente del proveedor'), ('responded', 'Respondida al cliente'), ('accepted', 'Aceptada por el cliente'), ('rejected', 'Rechazada por el cliente'), ('closed', 'Cerrada')], db_index=True, default='submitted', max_length=24, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tax_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='NIF / VAT'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='confirmed_total',
            field=models.DecimalField(decimal_places=2, help_text='Importe comercial final confirmado de la oferta. Es la referencia para preparar el pago y debe incluir el envío calculado para el destino cotizado cuando corresponda.', max_digits=12, verbose_name='total confirmado'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='currency',
            field=models.CharField(default='EUR', help_text='Código ISO 4217 de la moneda del total confirmado.', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='customer_message',
            field=models.TextField(blank=True, verbose_name='mensaje para el cliente'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='notas internas'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='lead_time_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='plazo estimado'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='reference_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='código de referencia'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada al cliente'), ('accepted', 'Aceptada por el cliente'), ('rejected', 'Rechazada por el cliente'), ('expired', 'Caducada')], db_index=True, default='draft', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='notas internas'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe a pagar'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='provider',
            field=models.CharField(default='manual', max_length=24, verbose_name='proveedor de pago'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=128, verbose_name='referencia del proveedor'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='reference_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='código de referencia'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=16, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_customer_type',
            field=models.CharField(choices=[('private', 'Particular'), ('company', 'Empresa o profesional')], default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_name',
            field=models.CharField(max_length=180, verbose_name='nombre o razón social de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_tax_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='NIF / VAT de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_phone',
            field=models.CharField(max_length=50, verbose_name='teléfono de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_recipient_name',
            field=models.CharField(max_length=180, verbose_name='destinatario del envío'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico del cliente'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=5, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='notes_from_customer',
            field=models.TextField(blank=True, verbose_name='notas del cliente'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='reference_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='código de referencia'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='tax_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='NIF / VAT'),
        ),
    ]
