# Generated by Django 5.2.13 on 2026-07-15 14:31

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_attributedefinition_allows_multiple_values_and_more'),
        ('inquiries', '0011_alter_inquiry_options_alter_inquiryitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad de destino'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='país de destino'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='destination_postal_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='código postal de destino'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='destination_region',
            field=models.CharField(blank=True, max_length=120, verbose_name='provincia o región'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='negative_resolution_customer_message',
            field=models.TextField(blank=True, verbose_name='mensaje de resolución para el cliente'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='negative_resolution_internal_notes',
            field=models.TextField(blank=True, verbose_name='notas internas de la resolución'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='negative_resolution_reason',
            field=models.CharField(blank=True, choices=[('unavailable', 'No disponible'), ('supplier_cannot_confirm', 'El proveedor no puede confirmar'), ('logistics_not_possible', 'Logística no viable'), ('other', 'Otro motivo')], db_index=True, max_length=40, verbose_name='motivo de resolución no ofertable'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='negative_resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='resuelta como no ofertable el'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='response_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha límite de respuesta'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='submission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='inquiries.inquirysubmissiongroup', verbose_name='grupo de solicitudes'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='supplier_feedback_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='respuesta del proveedor recibida el'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='nota del cliente'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inquiries.inquiry', verbose_name='solicitud'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='last_known_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='último precio conocido al solicitar'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_items', to='catalog.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad solicitada'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='aceptada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='token de acceso'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='caducada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='inquiries.inquiry', verbose_name='solicitud'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='offer_response_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha límite de respuesta'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='payment_deadline_hours_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='horas de pago aplicadas'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='quoted_destination_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad cotizada'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='quoted_destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='país cotizado'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='quoted_destination_postal_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='código postal cotizado'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='quoted_destination_region',
            field=models.CharField(blank=True, max_length=120, verbose_name='provincia o región cotizada'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='rechazada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='response_deadline_hours_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='horas de respuesta aplicadas'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='enviada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='cancelado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='failed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fallido el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='initiated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='iniciado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='inquiries.inquiryoffer', verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='pagado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='payment_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha límite de pago'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_address_line_1',
            field=models.CharField(max_length=255, verbose_name='dirección de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='información adicional de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_city',
            field=models.CharField(max_length=120, verbose_name='ciudad de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='país de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_customer_type',
            field=models.CharField(choices=[('private', 'Particular'), ('company', 'Empresa o profesional')], default='private', max_length=16, verbose_name='tipo de cliente de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_postal_code',
            field=models.CharField(max_length=32, verbose_name='código postal de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_region',
            field=models.CharField(max_length=120, verbose_name='provincia o región de facturación'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_same_as_shipping',
            field=models.BooleanField(default=True, verbose_name='facturación igual que envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='completado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_details', to='inquiries.inquiryofferpayment', verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_address_line_1',
            field=models.CharField(max_length=255, verbose_name='dirección de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='información adicional de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_city',
            field=models.CharField(max_length=120, verbose_name='ciudad de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='país de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_postal_code',
            field=models.CharField(max_length=32, verbose_name='código postal de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_region',
            field=models.CharField(max_length=120, verbose_name='provincia o región de envío'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad de destino'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='destination_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='país de destino'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='destination_postal_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='código postal de destino'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='destination_region',
            field=models.CharField(blank=True, max_length=120, verbose_name='provincia o región'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='inquirysubmissiongroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_submission_groups', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
