# Generated by Django 5.2.13 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0012_alter_inquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_tax_id',
            field=models.CharField(max_length=64, verbose_name='NIF / VAT de facturación'),
        ),
    ]
