# Generated by Django 5.2.13 on 2026-07-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0014_unify_offer_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryoffer',
            name='cancellation_customer_message',
            field=models.TextField(blank=True, verbose_name='mensaje de cancelación para el cliente'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='cancellation_internal_reason',
            field=models.TextField(blank=True, verbose_name='motivo interno de cancelación'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='cancelada el'),
        ),
        migrations.AlterField(
            model_name='inquiryoffer',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada al cliente'), ('accepted', 'Aceptada por el cliente'), ('rejected', 'Rechazada por el cliente'), ('expired', 'Caducada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=16, verbose_name='estado'),
        ),
    ]
