# Generated by Django 5.2.13 on 2026-07-19 14:57

from decimal import Decimal
from django.db import migrations, models


def preserve_existing_offer_totals(apps, schema_editor):
    InquiryOffer = apps.get_model("inquiries", "InquiryOffer")
    InquiryOffer.objects.update(
        product_price=models.F("confirmed_total"),
        product_vat_applicable=False,
        shipping_vat_applicable=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0015_inquiryoffer_cancellation_customer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryoffer',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio neto del producto antes de aplicar el IVA indicado.', max_digits=12, null=True, verbose_name='precio del producto sin IVA'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='product_vat_applicable',
            field=models.BooleanField(default=True, verbose_name='aplicar IVA al producto'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='product_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA del producto (%)'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe neto del envío antes de aplicar el IVA indicado.', max_digits=12, verbose_name='gastos de envío sin IVA'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='shipping_vat_applicable',
            field=models.BooleanField(default=True, verbose_name='aplicar IVA al envío'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='shipping_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='IVA del envío (%)'),
        ),
        migrations.RunPython(preserve_existing_offer_totals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inquiryoffer',
            constraint=models.CheckConstraint(condition=models.Q(('product_price__gte', 0), ('product_price__isnull', True), _connector='OR'), name='inq_offer_product_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='inquiryoffer',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_price__gte', 0)), name='inq_offer_shipping_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='inquiryoffer',
            constraint=models.CheckConstraint(condition=models.Q(('product_vat_rate__gte', 0), ('product_vat_rate__lte', 100)), name='inq_offer_product_vat_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='inquiryoffer',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_vat_rate__gte', 0), ('shipping_vat_rate__lte', 100)), name='inq_offer_shipping_vat_range_ck'),
        ),
    ]
