# Generated by Django 5.2.13 on 2026-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0016_inquiryoffer_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryoffer',
            name='update_product_last_known_price',
            field=models.BooleanField(default=True, help_text='Al enviar la oferta, actualiza el último precio conocido de la web pública con el precio unitario sin IVA (precio del producto dividido entre la cantidad solicitada), junto con su porcentaje de IVA.', verbose_name='actualizar el último precio conocido del producto'),
        ),
    ]
