# Generated by Django 5.2.13 on 2026-07-20 11:08

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


LEGACY_EXEMPTION_REASON = "Importe heredado sin desglose de IVA"


def backfill_tax_exemption_reasons(apps, schema_editor):
    del schema_editor
    InquiryOffer = apps.get_model("inquiries", "InquiryOffer")
    InquiryOffer.objects.filter(product_vat_applicable=False).update(
        product_tax_exemption_reason=LEGACY_EXEMPTION_REASON
    )
    InquiryOffer.objects.filter(shipping_vat_applicable=False).update(
        shipping_tax_exemption_reason=LEGACY_EXEMPTION_REASON
    )


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0017_inquiryoffer_update_product_last_known_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIssuerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180, verbose_name='razón social')),
                ('tax_id', models.CharField(max_length=64, verbose_name='NIF / VAT')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='domicilio fiscal')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='información adicional del domicilio fiscal')),
                ('city', models.CharField(max_length=120, verbose_name='ciudad')),
                ('region', models.CharField(max_length=120, verbose_name='provincia o región')),
                ('postal_code', models.CharField(max_length=32, verbose_name='código postal')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='país')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=50, verbose_name='teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada el')),
            ],
            options={
                'verbose_name': 'configuración fiscal del emisor',
                'verbose_name_plural': 'configuración fiscal del emisor',
            },
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='product_tax_exemption_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motivo fiscal del producto sin IVA'),
        ),
        migrations.AddField(
            model_name='inquiryoffer',
            name='shipping_tax_exemption_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motivo fiscal del envío sin IVA'),
        ),
        migrations.RunPython(backfill_tax_exemption_reasons, noop_reverse),
        migrations.AddField(
            model_name='inquiryofferpayment',
            name='provider_transaction_reference',
            field=models.CharField(blank=True, max_length=128, verbose_name='referencia de la transacción del proveedor'),
        ),
        migrations.CreateModel(
            name='PaymentInvoiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=32, verbose_name='referencia del pago')),
                ('offer_reference', models.CharField(max_length=32, verbose_name='referencia de la oferta')),
                ('inquiry_reference', models.CharField(max_length=32, verbose_name='referencia de la solicitud')),
                ('paid_at', models.DateTimeField(verbose_name='pagado el')),
                ('provider', models.CharField(max_length=24, verbose_name='proveedor de pago')),
                ('checkout_reference', models.CharField(blank=True, max_length=128, verbose_name='referencia de Checkout')),
                ('transaction_reference', models.CharField(blank=True, max_length=128, verbose_name='referencia de la transacción')),
                ('currency', models.CharField(max_length=3, verbose_name='moneda')),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base imponible total')),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='impuestos totales')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total cobrado')),
                ('customer_type', models.CharField(max_length=16, verbose_name='tipo de cliente')),
                ('customer_name', models.CharField(max_length=180, verbose_name='nombre o razón social del cliente')),
                ('customer_tax_id', models.CharField(max_length=64, verbose_name='NIF / VAT del cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='correo del cliente')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='teléfono del cliente')),
                ('customer_address_line_1', models.CharField(max_length=255, verbose_name='domicilio fiscal del cliente')),
                ('customer_address_line_2', models.CharField(blank=True, max_length=255, verbose_name='información adicional del domicilio del cliente')),
                ('customer_city', models.CharField(max_length=120, verbose_name='ciudad del cliente')),
                ('customer_region', models.CharField(max_length=120, verbose_name='provincia o región del cliente')),
                ('customer_postal_code', models.CharField(max_length=32, verbose_name='código postal del cliente')),
                ('customer_country', django_countries.fields.CountryField(max_length=2, verbose_name='país del cliente')),
                ('issuer_legal_name', models.CharField(max_length=180, verbose_name='razón social del emisor')),
                ('issuer_tax_id', models.CharField(max_length=64, verbose_name='NIF / VAT del emisor')),
                ('issuer_address_line_1', models.CharField(max_length=255, verbose_name='domicilio fiscal del emisor')),
                ('issuer_address_line_2', models.CharField(blank=True, max_length=255, verbose_name='información adicional del domicilio del emisor')),
                ('issuer_city', models.CharField(max_length=120, verbose_name='ciudad del emisor')),
                ('issuer_region', models.CharField(max_length=120, verbose_name='provincia o región del emisor')),
                ('issuer_postal_code', models.CharField(max_length=32, verbose_name='código postal del emisor')),
                ('issuer_country', django_countries.fields.CountryField(max_length=2, verbose_name='país del emisor')),
                ('issuer_email', models.EmailField(max_length=254, verbose_name='correo del emisor')),
                ('issuer_phone', models.CharField(max_length=50, verbose_name='teléfono del emisor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_snapshot', to='inquiries.inquiryofferpayment', verbose_name='pago')),
            ],
            options={
                'verbose_name': 'snapshot fiscal del pago',
                'verbose_name_plural': 'snapshots fiscales de pagos',
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoiceLineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('product', 'Producto'), ('shipping', 'Transporte')], max_length=16, verbose_name='tipo')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU / referencia')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_net_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='precio unitario sin impuestos')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base imponible')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tipo impositivo (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe de impuestos')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('tax_exemption_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo fiscal sin impuestos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inquiries.paymentinvoicesnapshot', verbose_name='snapshot fiscal')),
            ],
            options={
                'verbose_name': 'línea del snapshot fiscal',
                'verbose_name_plural': 'líneas del snapshot fiscal',
                'ordering': ('id',),
            },
        ),
    ]
