# Generated by Django 5.2.13 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0018_invoiceissuerconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryofferpaymentdetails',
            name='billing_company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='empresa o razón social de facturación'),
        ),
        migrations.AddField(
            model_name='inquiryofferpaymentdetails',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre de facturación'),
        ),
        migrations.AddField(
            model_name='inquiryofferpaymentdetails',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellidos de facturación'),
        ),
        migrations.AddField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre del destinatario'),
        ),
        migrations.AddField(
            model_name='inquiryofferpaymentdetails',
            name='shipping_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellidos del destinatario'),
        ),
        migrations.AlterField(
            model_name='inquiryofferpaymentdetails',
            name='billing_customer_type',
            field=models.CharField(choices=[('private', 'Particular'), ('company', 'Empresa')], default='private', max_length=16, verbose_name='tipo de cliente de facturación'),
        ),
    ]
