# Generated by Django 5.2.13 on 2026-04-10 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='supplier_imports/%Y/%m/%d/')),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=24)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='suppliers.supplier')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalog.product')),
                ('supplier_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.supplierimport')),
            ],
            options={
                'ordering': ['supplier_import', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierimport',
            index=models.Index(fields=['supplier', 'import_status'], name='imports_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierimport',
            index=models.Index(fields=['created_at'], name='imports_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierimportrow',
            index=models.Index(fields=['supplier_import', 'processing_status'], name='imports_row_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierimportrow',
            index=models.Index(fields=['linked_product'], name='imports_row_linked_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierimportrow',
            constraint=models.UniqueConstraint(fields=('supplier_import', 'row_number'), name='imports_row_import_row_number_uq'),
        ),
    ]
