# Generated by Django 5.2.13 on 2026-04-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierimport',
            name='processing_notes',
            field=models.TextField(blank=True),
        ),
    ]
