# Generated by Django 5.2.13 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_supplierimport_processing_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierimport',
            options={'ordering': ['-created_at'], 'verbose_name': 'importación de proveedor', 'verbose_name_plural': 'importaciones de proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplierimportrow',
            options={'ordering': ['supplier_import', 'row_number'], 'verbose_name': 'fila de importación', 'verbose_name_plural': 'filas de importación'},
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='filas con error'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='import_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('completed', 'Completada'), ('completed_with_errors', 'Completada con errores'), ('failed', 'Fallida')], db_index=True, default='pending', max_length=24, verbose_name='estado de importación'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='processing_notes',
            field=models.TextField(blank=True, verbose_name='notas de procesamiento'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='successful_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='filas correctas'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='filas totales'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='mensaje de error'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Correcta'), ('skipped', 'Omitida'), ('error', 'Error')], db_index=True, default='pending', max_length=20, verbose_name='estado de procesamiento'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='datos originales'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='row_number',
            field=models.PositiveIntegerField(verbose_name='número de fila'),
        ),
    ]
