# Generated by Django 5.2.13 on 2026-07-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_attributedefinition_allows_multiple_values_and_more'),
        ('imports', '0003_alter_supplierimport_options_and_more'),
        ('suppliers', '0009_alter_supplier_accepted_payment_deadline_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finalizada el'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='supplier_imports/%Y/%m/%d/', verbose_name='archivo original'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='iniciada el'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='suppliers.supplier', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='supplierimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_imports', to=settings.AUTH_USER_MODEL, verbose_name='subida por'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalog.product', verbose_name='producto vinculado'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='supplier_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.supplierimport', verbose_name='importación de proveedor'),
        ),
        migrations.AlterField(
            model_name='supplierimportrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
    ]
