# Generated by Django 5.2.13 on 2026-04-11 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['supplier__name', 'user__username'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='sup_uasg_user_act_idx'), models.Index(fields=['supplier', 'is_active'], name='sup_uasg_sup_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'user'), name='sup_user_assignment_supplier_user_uq')],
            },
        ),
    ]
