# Generated by Django 5.2.13 on 2026-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplieruserassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='orders_email',
            field=models.EmailField(blank=True, help_text='Operational mailbox for orders, confirmed offers, and availability updates.', max_length=254),
        ),
    ]
