# Generated by Django 5.2.13 on 2026-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='auto_send_offer_sent_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when a customer-facing offer is sent.'),
        ),
    ]
