# Generated by Django 5.2.13 on 2026-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_auto_send_offer_sent_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='auto_send_inquiry_submitted_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier inquiry notification when a customer inquiry is submitted.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inquiry_submitted_email_body_template',
            field=models.TextField(blank=True, help_text='Optional body template for automatic supplier inquiry notifications. Supports Django template variables such as inquiry, supplier, and items.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inquiry_submitted_email_subject_template',
            field=models.TextField(blank=True, help_text='Optional subject template for automatic supplier inquiry notifications. Supports Django template variables such as inquiry, supplier, and items.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_sent_email_body_template',
            field=models.TextField(blank=True, help_text='Optional body template for automatic supplier offer-sent notifications. Supports Django template variables such as offer, inquiry, supplier, and items.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_sent_email_subject_template',
            field=models.TextField(blank=True, help_text='Optional subject template for automatic supplier offer-sent notifications. Supports Django template variables such as offer, inquiry, supplier, and items.'),
        ),
    ]
