# Generated by Django 5.2.13 on 2026-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_auto_send_inquiry_submitted_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='auto_send_offer_accepted_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when a customer accepts an offer.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_send_offer_rejected_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when a customer rejects an offer.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_send_payment_paid_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when customer payment is confirmed.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inquiry_submitted_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when a customer inquiry is submitted. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_accepted_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when a customer accepts an offer. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_rejected_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when a customer rejects an offer. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_sent_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when an offer is sent to the customer. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_paid_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when customer payment is confirmed. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='send_inquiry_submitted_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='When enabled, sends an internal BCC copy for automatic supplier inquiry submitted notifications.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='send_offer_accepted_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='When enabled, sends an internal BCC copy for automatic supplier offer-accepted notifications.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='send_offer_rejected_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='When enabled, sends an internal BCC copy for automatic supplier offer-rejected notifications.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='send_offer_sent_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='When enabled, sends an internal BCC copy for automatic supplier offer-sent notifications.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='send_payment_paid_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='When enabled, sends an internal BCC copy for automatic supplier payment-paid notifications.'),
        ),
    ]
