# Generated by Django 5.2.13 on 2026-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_auto_send_offer_accepted_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='accepted_payment_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Maximum number of hours a customer has to pay after accepting an offer.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_send_offer_expired_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when a customer offer expires without response.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='auto_send_payment_expired_notification',
            field=models.BooleanField(default=False, help_text='Enable automatic supplier notification when an accepted offer payment window expires.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_expired_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when a customer offer expires without response. Falls back to orders_email when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='offer_response_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Maximum number of hours a customer has to accept or reject an offer once sent.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_expired_notification_email',
            field=models.EmailField(blank=True, help_text='Optional destination for automatic supplier notifications when an accepted offer payment window expires. Falls back to orders_email when empty.', max_length=254),
        ),
    ]
