# Generated by Django 5.2.13 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplier_accepted_payment_deadline_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplieruserassignment',
            options={'ordering': ['supplier__name', 'user__username'], 'verbose_name': 'asignación de usuario a proveedor', 'verbose_name_plural': 'asignaciones de usuarios a proveedores'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='persona de contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='sitio web'),
        ),
        migrations.AlterField(
            model_name='supplieruserassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activa'),
        ),
    ]
