# Generated by Django 5.2.13 on 2026-07-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='accepted_payment_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Número máximo de horas para pagar después de aceptar una oferta.', verbose_name='horas para pagar una oferta aceptada'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_inquiry_submitted_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor al recibir una solicitud.', verbose_name='enviar automáticamente al recibir una solicitud'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_offer_accepted_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando el cliente acepta una oferta.', verbose_name='enviar automáticamente al aceptar una oferta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_offer_expired_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando una oferta caduca sin respuesta.', verbose_name='enviar automáticamente al caducar una oferta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_offer_rejected_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando el cliente rechaza una oferta.', verbose_name='enviar automáticamente al rechazar una oferta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_offer_sent_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando se envía una oferta.', verbose_name='enviar automáticamente al enviar una oferta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_payment_expired_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando caduca el plazo de pago.', verbose_name='enviar automáticamente al caducar un pago'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='auto_send_payment_paid_notification',
            field=models.BooleanField(default=False, help_text='Activa el aviso automático al proveedor cuando se confirma el pago.', verbose_name='enviar automáticamente al confirmar un pago'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inquiry_submitted_email_body_template',
            field=models.TextField(blank=True, help_text='Plantilla opcional del cuerpo. Admite variables de Django como inquiry, supplier e items.', verbose_name='plantilla del cuerpo para nuevas solicitudes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inquiry_submitted_email_subject_template',
            field=models.TextField(blank=True, help_text='Plantilla opcional del asunto. Admite variables de Django como inquiry, supplier e items.', verbose_name='plantilla del asunto para nuevas solicitudes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inquiry_submitted_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de nuevas solicitudes. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para nuevas solicitudes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_accepted_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de ofertas aceptadas. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para ofertas aceptadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_expired_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de ofertas caducadas. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para ofertas caducadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_rejected_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de ofertas rechazadas. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para ofertas rechazadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_response_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Número máximo de horas para que el cliente acepte o rechace una oferta enviada.', verbose_name='horas para responder a la oferta'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_sent_email_body_template',
            field=models.TextField(blank=True, help_text='Plantilla opcional del cuerpo. Admite variables de Django como offer, inquiry, supplier e items.', verbose_name='plantilla del cuerpo para ofertas enviadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_sent_email_subject_template',
            field=models.TextField(blank=True, help_text='Plantilla opcional del asunto. Admite variables de Django como offer, inquiry, supplier e items.', verbose_name='plantilla del asunto para ofertas enviadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='offer_sent_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de ofertas enviadas. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para ofertas enviadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='orders_email',
            field=models.EmailField(blank=True, help_text='Buzón operativo para pedidos, ofertas confirmadas y actualizaciones de disponibilidad.', max_length=254, verbose_name='correo de pedidos'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_expired_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de pagos caducados. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para pagos caducados'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_paid_notification_email',
            field=models.EmailField(blank=True, help_text='Destino opcional para avisos de pagos confirmados. Si está vacío, se usa el correo de pedidos.', max_length=254, verbose_name='correo para pagos confirmados'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='send_inquiry_submitted_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='Envía una copia interna oculta de los avisos automáticos de nuevas solicitudes.', verbose_name='enviar copia interna de nuevas solicitudes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='send_offer_accepted_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='Envía una copia interna oculta de los avisos de ofertas aceptadas.', verbose_name='enviar copia interna de ofertas aceptadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='send_offer_rejected_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='Envía una copia interna oculta de los avisos de ofertas rechazadas.', verbose_name='enviar copia interna de ofertas rechazadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='send_offer_sent_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='Envía una copia interna oculta de los avisos de ofertas enviadas.', verbose_name='enviar copia interna de ofertas enviadas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='send_payment_paid_notification_internal_copy',
            field=models.BooleanField(default=False, help_text='Envía una copia interna oculta de los avisos de pagos confirmados.', verbose_name='enviar copia interna de pagos confirmados'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=180, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='supplieruserassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='supplieruserassignment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='suppliers.supplier', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='supplieruserassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='supplieruserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_assignments', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
