# Generated by Django 5.2.13 on 2026-04-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], db_index=True, default='text', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('is_filterable', models.BooleanField(db_index=True, default=True)),
                ('is_visible_on_product', models.BooleanField(db_index=True, default=True)),
                ('allows_multiple_values', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_filterable', 'sort_order'], name='cat_attr_filter_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('brand_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('parts', 'Parts'), ('both', 'Both')], default='parts', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['brand_type', 'is_active'], name='catalog_brand_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='cat_cond_active_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, max_length=64, null=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('short_description', models.CharField(blank=True, max_length=280)),
                ('long_description', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('price_visibility_mode', models.CharField(choices=[('hidden', 'Hidden'), ('visible_info', 'Visible (Last Known Price)')], db_index=True, default='hidden', max_length=20)),
                ('last_known_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('unit_of_sale', models.CharField(default='unit', max_length=32)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.condition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_raw', models.CharField(max_length=128)),
                ('number_normalized', models.CharField(db_index=True, editable=False, max_length=128)),
                ('part_number_type', models.CharField(choices=[('internal', 'Internal'), ('oe', 'OE'), ('oem', 'OEM'), ('equivalent', 'Equivalent'), ('legacy', 'Legacy')], db_index=True, default='internal', max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_numbers', to='catalog.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.product')),
            ],
            options={
                'ordering': ['number_normalized'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_normalized', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.attributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
            options={
                'ordering': ['attribute_definition__sort_order', 'attribute_definition__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='cat_cat_active_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='catalog_category_parent_name_uq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['publication_status', 'is_active'], name='cat_prod_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_visibility_mode', 'is_active'], name='catalog_product_price_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='cat_prod_brand_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_product_code__isnull', False), models.Q(('supplier_product_code', ''), _negated=True)), fields=('supplier', 'supplier_product_code'), name='catalog_product_supplier_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='catalog_product_pub_requires_date_ck'),
        ),
        migrations.AddIndex(
            model_name='partnumber',
            index=models.Index(fields=['part_number_type', 'number_normalized'], name='cat_pn_type_norm_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(fields=('product', 'number_normalized', 'part_number_type'), name='catalog_partnumber_product_number_type_uq'),
        ),
        migrations.AddConstraint(
            model_name='partnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='catalog_partnumber_primary_per_product_uq'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute_definition', 'value_normalized'], name='catalog_pav_attr_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_text__gt', ''), ('value_number__isnull', True), ('value_boolean__isnull', True)), models.Q(('value_text', ''), ('value_number__isnull', False), ('value_boolean__isnull', True)), models.Q(('value_text', ''), ('value_number__isnull', True), ('value_boolean__isnull', False)), _connector='OR'), name='catalog_pav_exactly_one_value_ck'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_definition', 'value_normalized'), name='catalog_pav_product_attr_value_uq'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='cat_img_prod_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='catalog_productimage_primary_per_product_uq'),
        ),
    ]
