# Generated by Django 5.2.13 on 2026-04-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'permissions': [('can_publish_product', 'Can publish product')]},
        ),
    ]
