# Generated by Django 5.2.13 on 2026-04-12 21:32

import django.db.models.deletion
from django.db import migrations, models

BASE_PART_NUMBER_TYPES = ("OEM", "OES", "AIM")


def seed_base_part_number_types(apps, schema_editor):
    PartNumberType = apps.get_model("catalog", "PartNumberType")

    for sort_order, code in enumerate(BASE_PART_NUMBER_TYPES, start=1):
        PartNumberType.objects.update_or_create(
            code=code,
            defaults={
                "name": code,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def map_existing_part_number_types(apps, schema_editor):
    PartNumber = apps.get_model("catalog", "PartNumber")
    PartNumberType = apps.get_model("catalog", "PartNumberType")

    type_ids = {
        code: PartNumberType.objects.only("id").get(code=code).id
        for code in BASE_PART_NUMBER_TYPES
    }

    PartNumber.objects.filter(part_number_type="oem").update(
        part_number_type_fk_id=type_ids["OEM"],
    )
    PartNumber.objects.filter(part_number_type="oe").update(
        part_number_type_fk_id=type_ids["OES"],
    )
    PartNumber.objects.exclude(part_number_type__in=("oem", "oe")).update(
        part_number_type_fk_id=type_ids["AIM"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, max_length=180, unique=True),
        ),
        migrations.CreateModel(
            name="PartNumberType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="cat_pntype_active_sort_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_base_part_number_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name="partnumber",
            name="part_number_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.partnumbertype",
            ),
        ),
        migrations.RunPython(map_existing_part_number_types, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="partnumber",
            name="catalog_partnumber_product_number_type_uq",
        ),
        migrations.RemoveIndex(
            model_name="partnumber",
            name="cat_pn_type_norm_idx",
        ),
        migrations.RemoveField(
            model_name="partnumber",
            name="part_number_type",
        ),
        migrations.RenameField(
            model_name="partnumber",
            old_name="part_number_type_fk",
            new_name="part_number_type",
        ),
        migrations.AlterField(
            model_name="partnumber",
            name="part_number_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_numbers",
                to="catalog.partnumbertype",
            ),
        ),
        migrations.AddIndex(
            model_name="partnumber",
            index=models.Index(
                fields=["part_number_type", "number_normalized"],
                name="cat_pn_type_norm_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnumber",
            constraint=models.UniqueConstraint(
                fields=("product", "number_normalized", "part_number_type"),
                name="catalog_partnumber_product_number_type_uq",
            ),
        ),
    ]
