# Generated by Django 5.2.13 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_slug_partnumbertype_and_more'),
        ('suppliers', '0002_supplieruserassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_quantity',
            field=models.CharField(default='Pcs', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='catalog_product_quantity_gte_1_ck'),
        ),
    ]
