# Generated by Django 5.2.13 on 2026-04-13 18:14

import django.db.models.deletion
from django.db import migrations, models


def backfill_oem_reference_brand(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    PartNumber = apps.get_model("catalog", "PartNumber")
    PartNumberType = apps.get_model("catalog", "PartNumberType")

    oem_part_number_type = PartNumberType.objects.filter(code="OEM").only("id").first()

    for product in Product.objects.filter(oem_reference_brand__isnull=True).only("id", "brand_id"):
        brand_id = product.brand_id

        if brand_id is None and oem_part_number_type is not None:
            brand_id = (
                PartNumber.objects.filter(
                    product_id=product.id,
                    part_number_type_id=oem_part_number_type.id,
                    is_primary=True,
                )
                .values_list("brand_id", flat=True)
                .first()
            )

        if brand_id is None and oem_part_number_type is not None:
            brand_id = (
                PartNumber.objects.filter(
                    product_id=product.id,
                    part_number_type_id=oem_part_number_type.id,
                )
                .exclude(brand_id__isnull=True)
                .values_list("brand_id", flat=True)
                .first()
            )

        if brand_id is not None:
            Product.objects.filter(pk=product.id, oem_reference_brand__isnull=True).update(
                oem_reference_brand_id=brand_id
            )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_quantity_product_unit_of_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oem_reference_brand',
            field=models.ForeignKey(help_text='Marca fabricante asociada a la referencia OEM principal (no la marca del vehículo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oem_reference_products', to='catalog.brand', verbose_name='Marca'),
        ),
        migrations.RunPython(backfill_oem_reference_brand, noop_reverse),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Referencia OEM principal del producto.', max_length=64, unique=True, verbose_name='Referencia (OEM)'),
        ),
    ]
