# Generated by Django 5.2.13 on 2026-04-13 18:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_brand_from_oem_reference_brand(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(brand__isnull=True, oem_reference_brand__isnull=False).update(
        brand_id=models.F("oem_reference_brand_id")
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_oem_reference_brand_alter_product_sku'),
    ]

    operations = [
        migrations.RunPython(backfill_brand_from_oem_reference_brand, noop_reverse),
        migrations.RemoveField(
            model_name='product',
            name='oem_reference_brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca fabricante asociada a la referencia OEM principal (no la marca del vehículo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marca'),
        ),
    ]
