# Generated by Django 5.2.13 on 2026-07-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_oem_reference_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca fabricante asociada a la referencia OE (no la marca del vehículo)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Referencia OE principal del producto', max_length=64, unique=True, verbose_name='Código de Fabricante (OES/OE)'),
        ),
    ]
