# Generated by Django 5.2.13 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_brand_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributedefinition',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'definición de atributo', 'verbose_name_plural': 'definiciones de atributos'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name'], 'verbose_name': 'estado del producto', 'verbose_name_plural': 'estados de los productos'},
        ),
        migrations.AlterModelOptions(
            name='partnumber',
            options={'ordering': ['number_normalized'], 'verbose_name': 'referencia de pieza', 'verbose_name_plural': 'referencias de pieza'},
        ),
        migrations.AlterModelOptions(
            name='partnumbertype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'tipo de referencia de pieza', 'verbose_name_plural': 'tipos de referencia de pieza'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'permissions': [('can_publish_product', 'Puede publicar productos')], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ['attribute_definition__sort_order', 'attribute_definition__name'], 'verbose_name': 'valor de atributo de producto', 'verbose_name_plural': 'valores de atributos de productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'imagen de producto', 'verbose_name_plural': 'imágenes de productos'},
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Sí/No')], db_index=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('vehicle', 'Vehículos'), ('parts', 'Recambios'), ('both', 'Vehículos y recambios')], default='parts', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_known_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='último precio conocido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='descripción completa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_visibility_mode',
            field=models.CharField(choices=[('hidden', 'Precio oculto'), ('visible_info', 'Visible (último precio conocido)')], db_index=True, default='hidden', max_length=20, verbose_name='visibilidad del precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('published', 'Publicado')], db_index=True, default='draft', max_length=20, verbose_name='estado de publicación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=280, verbose_name='descripción breve'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=220, verbose_name='título'),
        ),
    ]
