# Generated by Django 5.2.13 on 2026-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_attributedefinition_options_and_more'),
        ('suppliers', '0009_alter_supplier_accepted_payment_deadline_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedefinition',
            name='allows_multiple_values',
            field=models.BooleanField(db_index=True, default=False, verbose_name='admite varios valores'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('boolean', 'Sí/No')], db_index=True, default='text', max_length=20, verbose_name='tipo de dato'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='is_filterable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='filtrable'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='is_visible_on_product',
            field=models.BooleanField(db_index=True, default=True, verbose_name='visible en el producto'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='unit',
            field=models.CharField(blank=True, max_length=24, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('vehicle', 'Vehículos'), ('parts', 'Recambios'), ('both', 'Vehículos y recambios')], default='parts', max_length=20, verbose_name='tipo de marca'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='categoría superior'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_numbers', to='catalog.brand', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='number_normalized',
            field=models.CharField(db_index=True, editable=False, max_length=128, verbose_name='referencia normalizada'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='number_raw',
            field=models.CharField(max_length=128, verbose_name='referencia original'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='part_number_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='catalog.partnumbertype', verbose_name='tipo de referencia'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='catalog.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='partnumbertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.condition', verbose_name='estado del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='alto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='largo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=180, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='suppliers.supplier', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_product_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='código de producto del proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_quantity',
            field=models.CharField(default='Pcs', max_length=32, verbose_name='unidad de cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_sale',
            field=models.CharField(default='unit', max_length=32, verbose_name='unidad de venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ancho'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalog.attributedefinition', verbose_name='atributo'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True, verbose_name='valor Sí/No'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='valor normalizado'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='valor numérico'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='valor de texto'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='texto alternativo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada el'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizada el'),
        ),
    ]
