# Generated by Django 5.2.13 on 2026-07-19 15:40

from decimal import Decimal
from django.db import migrations, models


def backfill_last_known_price_updated_at(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    products = Product.objects.filter(last_known_price__isnull=False).iterator()
    for product in products:
        Product.objects.filter(pk=product.pk).update(
            last_known_price_updated_at=product.updated_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_attributedefinition_allows_multiple_values_and_more'),
        ('suppliers', '0010_unify_offer_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_known_price_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='último precio conocido actualizado el'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de IVA que se aplica al último precio conocido.', max_digits=5, verbose_name='IVA del producto (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_known_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario sin IVA.', max_digits=12, null=True, verbose_name='último precio conocido'),
        ),
        migrations.RunPython(
            backfill_last_known_price_updated_at,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_vat_rate__gte', 0), ('product_vat_rate__lte', 100)), name='catalog_product_vat_range_ck'),
        ),
    ]
